#!/usr/sbin/nft -f

flush ruleset

define STATELESS = {
#	2a01:4ff:1f0:7e46:0:0::/96,
	2a01:4ff:1f0:7e46:0:1::/96,
	2a01:4ff:1f0:7e46:0:2::/96,
	2a01:4ff:1f0:7e46:0:3::/96,
#	2a01:4ff:1f0:7e46:c4b0::/80,
	A000::/3,
}

table inet filter {
	chain skip1 {
		type filter hook output priority -300;
		notrack
	}
	chain skip2 {
		type filter hook prerouting priority -300;
		iif {eth0} notrack
#		ip6 daddr $STATELESS notrack
	}
	chain prerouting {
		type nat hook prerouting priority dstnat;
	}
	chain input {
		type filter hook input priority filter;
	}
	chain forward {
		type filter hook forward priority filter;
	}
	chain output {
		type filter hook output priority filter;
	}
	chain postrouting {
		type nat hook postrouting priority srcnat;
		ip6 saddr A000::/3 oif eth0 snat to 2a01:4ff:1f0:7e46:0:4::/96;
	}
}
