[package]
name = "masquerade"
version = "0.1.0"
edition = "2021"

[dependencies]
eyre = "0.6.12"
md5 = "0.7.0"
mio = { version = "1", features = ["net", "os-poll"] }
rand = "0.9.0"
slab = "0.4.9"
stun = { path = "../stun" }
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["fmt", "env-filter"] }
